// types.js
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';

export const FETCH_FILES_REQUEST = 'FETCH_FILES_REQUEST';
export const FETCH_FILES_SUCCESS = 'FETCH_FILES_SUCCESS';
export const FETCH_FILES_FAILURE = 'FETCH_FILES_FAILURE';
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const SET_SORT_OPTION = 'SET_SORT_OPTION';
export const SET_SORT_ORDER = 'SET_SORT_ORDER';
export const SET_SELECTED_FILES = 'SET_SELECTED_FILES';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_SELECTED_FILE_TYPE = 'SET_SELECTED_FILE_TYPE';
export const SET_SELECTED_CATEGORY = 'SET_SELECTED_CATEGORY';

export const UPLOAD_FILE_REQUEST = 'UPLOAD_FILE_REQUEST';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_FAILURE = 'UPLOAD_FILE_FAILURE';
export const SET_FILE_DETAILS = 'SET_FILE_DETAILS';
export const SET_CATEGORIES = 'SET_CATEGORIES';

export const DELETE_FILES_REQUEST = 'DELETE_FILES_REQUEST';
export const DELETE_FILES_SUCCESS = 'DELETE_FILES_SUCCESS';
export const DELETE_FILES_FAILURE = 'DELETE_FILES_FAILURE';