// Authentication
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';

// Modules
export const FETCH_MODULES_SUCCESS = "FETCH_MODULES_SUCCESS";
export const FETCH_MODULES_FAILURE = "FETCH_MODULES_FAILURE";

// Content
export const FETCH_CONTENT_REQUEST = "FETCH_CONTENT_REQUEST";
export const FETCH_CONTENT_SUCCESS = "FETCH_CONTENT_SUCCESS";
export const FETCH_CONTENT_FAILURE = "FETCH_CONTENT_FAILURE";
export const RESET_CONTENT = "RESET_CONTENT";

// Files
export const FETCH_FILES_REQUEST = 'FETCH_FILES_REQUEST';
export const FETCH_FILES_SUCCESS = 'FETCH_FILES_SUCCESS';
export const FETCH_FILES_FAILURE = 'FETCH_FILES_FAILURE';
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const SET_SORT_OPTION = 'SET_SORT_OPTION';
export const SET_SORT_ORDER = 'SET_SORT_ORDER';
export const SET_SELECTED_FILES = 'SET_SELECTED_FILES';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_SELECTED_FILE_TYPE = 'SET_SELECTED_FILE_TYPE';
export const SET_SELECTED_CATEGORY = 'SET_SELECTED_CATEGORY';

// Upload
export const UPLOAD_FILE_REQUEST = 'UPLOAD_FILE_REQUEST';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_FAILURE = 'UPLOAD_FILE_FAILURE';
export const SET_FILE_DETAILS = 'SET_FILE_DETAILS';
export const SET_CATEGORIES = 'SET_CATEGORIES';

// Delete
export const DELETE_FILES_REQUEST = 'DELETE_FILES_REQUEST';
export const DELETE_FILES_SUCCESS = 'DELETE_FILES_SUCCESS';
export const DELETE_FILES_FAILURE = 'DELETE_FILES_FAILURE';